# Generated by Django 2.1.5 on 2019-04-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('looking for a study buddy', 'looking for a study buddy'), ('looking for a study group', 'looking for a study group'), ('looking for a tutor', 'looking for a tutor'), ('available to tutor', 'available to tutor')], default='looking for a study buddy', max_length=50),
        ),
    ]
