# Generated by Django 2.1.7 on 2019-03-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190217_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.CharField(default='a club on Grounds', max_length=350),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='undeclared', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('first', 1), ('second', 2), ('third', 3), ('fourth', 4)], default='first', max_length=6),
        ),
    ]
