# Generated by Django 2.1.7 on 2019-02-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190222_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')], default='first', max_length=6),
        ),
    ]
