# Generated by Django 2.1.7 on 2019-02-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190222_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.CharField(default='a club on Grounds', max_length=350),
        ),
    ]
