# Generated by Django 2.1.7 on 2019-03-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
