# Generated by Django 2.1.7 on 2019-03-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='undeclared', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('first', 1), ('second', 2), ('third', 3), ('fourth', 4)], default='first', max_length=6),
        ),
    ]
