# Generated by Django 2.1.7 on 2019-03-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
