# Generated by Django 2.1.5 on 2019-03-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
