# Generated by Django 2.1.7 on 2019-03-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190318_1456'),
        ('profiles', '0015_remove_profile_image'),
    ]

    operations = [
    ]
