# Generated by Django 2.1.7 on 2019-03-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_merge_20190324_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
