# Generated by Django 2.1.5 on 2019-04-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='club',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='student',
        ),
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.AddField(
            model_name='club',
            name='profiles',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
