# Generated by Django 2.1.5 on 2019-04-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20190407_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='profiles',
            field=models.ManyToManyField(default=[], to='profiles.Profile'),
        ),
    ]
