# Generated by Django 2.1.7 on 2019-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20190405_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='School of Engineering', max_length=150),
        ),
    ]
