# Generated by Django 2.1.5 on 2019-04-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20190408_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('body', models.TextField(default='here is some post body text')),
                ('type', models.CharField(choices=[(1, 'event'), (2, 'announcement'), (3, 'misc')], default='announcement', max_length=6)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
