# Generated by Django 2.1.5 on 2019-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('event', 'event'), ('announcement', 'announcement'), ('misc', 'misc')], default='announcement', max_length=6),
        ),
    ]
